/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package petshop.GUI;

import javax.swing.JPanel;

/**
 *
 * @author matheus
 */
public class BarraDeMenu extends javax.swing.JFrame{
 
    public BarraDeMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        
        bmBarraMenu = new javax.swing.JMenuBar();
        mCadastro = new javax.swing.JMenu();
        miAnimal = new javax.swing.JMenuItem();
        miCliente = new javax.swing.JMenuItem();
        mClientes = new javax.swing.JMenu();
        miBuscarCliente = new javax.swing.JMenuItem();
        mAnimais = new javax.swing.JMenu();
        miBuscarAnimal = new javax.swing.JMenuItem();
        mAtendimento = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        miNovoAtendimento = new javax.swing.JMenuItem();
        miContultar = new javax.swing.JMenuItem();
        panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        panel.setPreferredSize(new java.awt.Dimension(700, 350));

        mCadastro.setText("Cadastro");

        miAnimal.setText("Animal");
        miAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAnimalActionPerformed(evt);
            }
        });
        mCadastro.add(miAnimal);

        miCliente.setText("Cliente");
        mCadastro.add(miCliente);

        bmBarraMenu.add(mCadastro);

        mClientes.setText("Clientes");

        miBuscarCliente.setText("Buscar");
        mClientes.add(miBuscarCliente);

        bmBarraMenu.add(mClientes);

        mAnimais.setText("Animais");

        miBuscarAnimal.setText("Buscar");
        mAnimais.add(miBuscarAnimal);

        bmBarraMenu.add(mAnimais);

        mAtendimento.setText("Atendimento");

        jMenuItem5.setText("Orçamento");
        mAtendimento.add(jMenuItem5);

        miNovoAtendimento.setText("Novo Atendimento");
        mAtendimento.add(miNovoAtendimento);

        miContultar.setText("Consultar");
        miContultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miContultarActionPerformed(evt);
            }
        });
        mAtendimento.add(miContultar);

        bmBarraMenu.add(mAtendimento);

        setJMenuBar(bmBarraMenu);
        
        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING));
        panelLayout.setVerticalGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING));
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );
       

        pack();
    }// </editor-fold>                        

    private void miAnimalActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void miContultarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                                                                 


    // Variables declaration - do not modify                     
    private javax.swing.JMenuBar bmBarraMenu;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenu mAnimais;
    private javax.swing.JMenu mAtendimento;
    private javax.swing.JMenu mCadastro;
    private javax.swing.JMenu mClientes;
    private javax.swing.JMenuItem miAnimal;
    private javax.swing.JMenuItem miBuscarAnimal;
    private javax.swing.JMenuItem miBuscarCliente;
    private javax.swing.JMenuItem miCliente;
    private javax.swing.JMenuItem miContultar;
    private javax.swing.JMenuItem miNovoAtendimento;
    private javax.swing.JPanel panel;

    public JPanel getPanel() {
        return panel;
    }

    public void setPanel(JPanel panel) {
        setContentPane(panel);
    }

    // End of variables declaration                   

 public void mudarPanel(javax.swing.JPanel panel){
        
        
    }
}

    

