/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package petshop.GUI;

import petshop.GUI.ConexaoPostgreSQL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author matheus
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    public void capslock(final javax.swing.JTextField txt) {
        txt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt.setText(txt.getText().toUpperCase());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexo = new javax.swing.ButtonGroup();
        pLogin = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        lbLogin = new javax.swing.JLabel();
        lbSenha = new javax.swing.JLabel();
        bEntrar = new javax.swing.JButton();
        bSair = new javax.swing.JButton();
        txtSenha = new javax.swing.JPasswordField();
        lbSenhaIncorreta = new javax.swing.JLabel();
        lbLoginIncorreto = new javax.swing.JLabel();
        nada = new javax.swing.JLabel();
        pMenuPrincipal = new javax.swing.JPanel();
        bClientes = new javax.swing.JButton();
        bServicos = new javax.swing.JButton();
        bAnimais = new javax.swing.JButton();
        bFuncionario = new javax.swing.JButton();
        bLogout = new javax.swing.JButton();
        lbAdmin = new javax.swing.JLabel();
        pAnimal = new javax.swing.JPanel();
        bNClientes4 = new javax.swing.JButton();
        bBClientes4 = new javax.swing.JButton();
        bVoltar4 = new javax.swing.JButton();
        txtAdmin2 = new javax.swing.JLabel();
        pClientes = new javax.swing.JPanel();
        bNClientes3 = new javax.swing.JButton();
        bBClientes3 = new javax.swing.JButton();
        bVoltar3 = new javax.swing.JButton();
        txtAdmin1 = new javax.swing.JLabel();
        pCadastroAnimal = new javax.swing.JPanel();
        bVoltar = new javax.swing.JButton();
        lbTitulo1 = new javax.swing.JLabel();
        bLimpar = new javax.swing.JButton();
        bSalvarCadastro = new javax.swing.JButton();
        rbMacho = new javax.swing.JRadioButton();
        rbFemea = new javax.swing.JRadioButton();
        txtNome = new javax.swing.JTextField();
        cbEspecie = new javax.swing.JComboBox();
        cbDono = new javax.swing.JComboBox();
        lbNome = new javax.swing.JLabel();
        lSexo = new javax.swing.JLabel();
        lbEspecie = new javax.swing.JLabel();
        lbRaca = new javax.swing.JLabel();
        lbDono = new javax.swing.JLabel();
        txtRaca = new javax.swing.JTextField();
        pAddCliente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNome1 = new javax.swing.JTextField();
        lbNome1 = new javax.swing.JLabel();
        txtEndereço = new javax.swing.JTextField();
        lbEndereço = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        lbComplemento = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        lbSexo = new javax.swing.JLabel();
        cbSexo = new javax.swing.JComboBox();
        lbcpf = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();
        lbDataNasc = new javax.swing.JLabel();
        txtDataNasc = new javax.swing.JFormattedTextField();
        lbTelefone1 = new javax.swing.JLabel();
        txtTelefone1 = new javax.swing.JFormattedTextField();
        lbTelefone2 = new javax.swing.JLabel();
        txtTelefone2 = new javax.swing.JFormattedTextField();
        lbFaltaNome = new javax.swing.JLabel();
        lbFaltaEnd = new javax.swing.JLabel();
        lbFaltaBairro = new javax.swing.JLabel();
        lbFaltaData = new javax.swing.JLabel();
        lbFaltaTel = new javax.swing.JLabel();
        lbFaltaComp = new javax.swing.JLabel();
        lbFaltaCpf = new javax.swing.JLabel();
        bLimpar1 = new javax.swing.JButton();
        bSalvar = new javax.swing.JButton();
        bVoltar1 = new javax.swing.JButton();
        lbFaltaSexo = new javax.swing.JLabel();
        lbFaltaMensagem = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        bmBarraMenu = new javax.swing.JMenuBar();
        mCadastro = new javax.swing.JMenu();
        miAnimal = new javax.swing.JMenuItem();
        miCliente = new javax.swing.JMenuItem();
        mClientes = new javax.swing.JMenu();
        miBuscarCliente = new javax.swing.JMenuItem();
        mAnimais = new javax.swing.JMenu();
        miBuscarAnimal = new javax.swing.JMenuItem();
        mAtendimento = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        miNovoAtendimento = new javax.swing.JMenuItem();
        miContultar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pLogin.setPreferredSize(new java.awt.Dimension(700, 350));

        lbTitulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("PET SHOP");

        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });

        lbLogin.setText("Login:");

        lbSenha.setText("Senha:");

        bEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshop/GUI/54.png"))); // NOI18N
        bEntrar.setText("Entrar");
        bEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEntrarActionPerformed(evt);
            }
        });

        bSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshop/GUI/52.png"))); // NOI18N
        bSair.setText("Sair");
        bSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSairActionPerformed(evt);
            }
        });

        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });

        lbSenhaIncorreta.setForeground(new java.awt.Color(255, 0, 0));
        lbSenhaIncorreta.setText("Senha incorreta");
        lbSenhaIncorreta.setVisible(false);

        lbLoginIncorreto.setForeground(new java.awt.Color(255, 0, 0));
        lbLoginIncorreto.setText("Login incorreto");
        lbLoginIncorreto.setVisible(false);

        javax.swing.GroupLayout pLoginLayout = new javax.swing.GroupLayout(pLogin);
        pLogin.setLayout(pLoginLayout);
        pLoginLayout.setHorizontalGroup(
            pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLoginLayout.createSequentialGroup()
                .addContainerGap(251, Short.MAX_VALUE)
                .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nada, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pLoginLayout.createSequentialGroup()
                        .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pLoginLayout.createSequentialGroup()
                                .addComponent(lbSenha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pLoginLayout.createSequentialGroup()
                                    .addComponent(bSair)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bEntrar))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pLoginLayout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(lbTitulo))
                                    .addGroup(pLoginLayout.createSequentialGroup()
                                        .addComponent(lbLogin)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbLoginIncorreto)
                            .addComponent(lbSenhaIncorreta))))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        pLoginLayout.setVerticalGroup(
            pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLoginLayout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(lbTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(nada, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLoginIncorreto)
                    .addComponent(lbLogin))
                .addGap(20, 20, 20)
                .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSenhaIncorreta, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bEntrar)
                    .addComponent(bSair))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pMenuPrincipal.setVisible(false);

        bClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshop/GUI/13.png"))); // NOI18N
        bClientes.setText("<html><body>CLIENTES</body></html>");
        bClientes.setToolTipText("");
        bClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClientesActionPerformed(evt);
            }
        });

        bServicos.setText("<html><body>SERVIÇOS</body></html>");
        bServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bServicosActionPerformed(evt);
            }
        });

        bAnimais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshop/GUI/77.png"))); // NOI18N
        bAnimais.setText("<html><body>ANIMAIS</body></html>");
        bAnimais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnimaisActionPerformed(evt);
            }
        });

        bFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshop/GUI/14.png"))); // NOI18N
        bFuncionario.setText("<html><body>FUNCIONÁRIOS</body></html>");
        bFuncionario.setEnabled(false);
        bFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFuncionarioActionPerformed(evt);
            }
        });

        bLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshop/GUI/52.png"))); // NOI18N
        bLogout.setText("<html><body>LOGOUT</body></html>");
        bLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogoutActionPerformed(evt);
            }
        });

        lbAdmin.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lbAdmin.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbAdmin.setText("ADMIN");

        javax.swing.GroupLayout pMenuPrincipalLayout = new javax.swing.GroupLayout(pMenuPrincipal);
        pMenuPrincipal.setLayout(pMenuPrincipalLayout);
        pMenuPrincipalLayout.setHorizontalGroup(
            pMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMenuPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbAdmin)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pMenuPrincipalLayout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addGroup(pMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addGroup(pMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bServicos, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAnimais, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMenuPrincipalLayout.createSequentialGroup()
                .addContainerGap(593, Short.MAX_VALUE)
                .addComponent(bLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pMenuPrincipalLayout.setVerticalGroup(
            pMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMenuPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAnimais, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(pMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bServicos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(bLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pAnimal.setVisible(false);
        pAnimal.setPreferredSize(new java.awt.Dimension(700, 350));

        bNClientes4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshop/GUI/77.png"))); // NOI18N
        bNClientes4.setText("<html><body>NOVO ANIMAL</body></html>");
        bNClientes4.setToolTipText("");
        bNClientes4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNClientes4ActionPerformed(evt);
            }
        });

        bBClientes4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshop/GUI/77.png"))); // NOI18N
        bBClientes4.setText("BUSCAR ANIMAL");
        bBClientes4.setToolTipText("");
        bBClientes4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBClientes4ActionPerformed(evt);
            }
        });

        bVoltar4.setText("<html><body>VOLTAR</body></html>");
        bVoltar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltar4ActionPerformed(evt);
            }
        });

        txtAdmin2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        txtAdmin2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        txtAdmin2.setText("ANIMAL");

        javax.swing.GroupLayout pAnimalLayout = new javax.swing.GroupLayout(pAnimal);
        pAnimal.setLayout(pAnimalLayout);
        pAnimalLayout.setHorizontalGroup(
            pAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAnimalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pAnimalLayout.createSequentialGroup()
                        .addComponent(bNClientes4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(bBClientes4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bVoltar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAdmin2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pAnimalLayout.setVerticalGroup(
            pAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAnimalLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(txtAdmin2)
                .addGap(51, 51, 51)
                .addGroup(pAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bNClientes4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBClientes4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(bVoltar4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pClientes.setVisible(false);
        pClientes.setPreferredSize(new java.awt.Dimension(700, 350));

        bNClientes3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshop/GUI/13.png"))); // NOI18N
        bNClientes3.setText("<html><body>NOVO CLIENTE</body></html>");
        bNClientes3.setToolTipText("");
        bNClientes3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNClientes3ActionPerformed(evt);
            }
        });

        bBClientes3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshop/GUI/13.png"))); // NOI18N
        bBClientes3.setText("BUSCAR CLIENTE");
        bBClientes3.setToolTipText("");
        bBClientes3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBClientes3ActionPerformed(evt);
            }
        });

        bVoltar3.setText("<html><body>VOLTAR</body></html>");
        bVoltar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltar3ActionPerformed(evt);
            }
        });

        txtAdmin1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        txtAdmin1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        txtAdmin1.setText("CLIENTES");

        javax.swing.GroupLayout pClientesLayout = new javax.swing.GroupLayout(pClientes);
        pClientes.setLayout(pClientesLayout);
        pClientesLayout.setHorizontalGroup(
            pClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pClientesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pClientesLayout.createSequentialGroup()
                        .addComponent(bNClientes3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(bBClientes3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bVoltar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAdmin1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pClientesLayout.setVerticalGroup(
            pClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pClientesLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(txtAdmin1)
                .addGap(54, 54, 54)
                .addGroup(pClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bNClientes3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBClientes3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(bVoltar3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        bVoltar.setText("<html><body>VOLTAR</body></html>");
        bVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarActionPerformed(evt);
            }
        });

        lbTitulo1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lbTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbTitulo1.setText("Animal");

        bLimpar.setText("LIMPAR");
        bLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimparActionPerformed(evt);
            }
        });

        bSalvarCadastro.setText("<html><body>SALVAR CADASTRO</body></html>");
        bSalvarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalvarCadastroActionPerformed(evt);
            }
        });

        bgSexo.add(rbMacho);
        rbMacho.setText("Macho");
        rbMacho.setActionCommand("Macho");

        bgSexo.add(rbFemea);
        rbFemea.setText("Fêmea");
        rbFemea.setActionCommand("Femea");

        capslock(txtNome);

        cbEspecie.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "CACHORRO", "GATO", "CAVALO", "PASSARO", "VEADO(KURAS)", "POKÉMON(PEDRO)" }));

        cbDono.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-" }));

        lbNome.setText("NOME:");

        lSexo.setText("SEXO:");

        lbEspecie.setText("ESPECIE:");

        lbRaca.setText("RAÇA:");

        lbDono.setText("DONO:");

        capslock(txtRaca);

        javax.swing.GroupLayout pCadastroAnimalLayout = new javax.swing.GroupLayout(pCadastroAnimal);
        pCadastroAnimal.setLayout(pCadastroAnimalLayout);
        pCadastroAnimalLayout.setHorizontalGroup(
            pCadastroAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCadastroAnimalLayout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addGroup(pCadastroAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbNome)
                    .addComponent(lSexo)
                    .addComponent(lbEspecie)
                    .addComponent(lbRaca)
                    .addComponent(lbDono))
                .addGap(18, 18, 18)
                .addGroup(pCadastroAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbEspecie, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pCadastroAnimalLayout.createSequentialGroup()
                        .addComponent(rbMacho)
                        .addGap(41, 41, 41)
                        .addComponent(rbFemea)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pCadastroAnimalLayout.createSequentialGroup()
                        .addGroup(pCadastroAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(bSalvarCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))
                    .addComponent(txtNome)
                    .addComponent(cbDono, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtRaca))
                .addContainerGap(137, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCadastroAnimalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTitulo1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pCadastroAnimalLayout.setVerticalGroup(
            pCadastroAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadastroAnimalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo1)
                .addGap(38, 38, 38)
                .addGroup(pCadastroAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNome))
                .addGap(18, 18, 18)
                .addGroup(pCadastroAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbMacho)
                    .addComponent(rbFemea)
                    .addComponent(lSexo))
                .addGap(18, 18, 18)
                .addGroup(pCadastroAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEspecie))
                .addGap(18, 18, 18)
                .addGroup(pCadastroAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRaca)
                    .addComponent(txtRaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pCadastroAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDono))
                .addGap(16, 16, 16)
                .addGroup(pCadastroAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCadastroAnimalLayout.createSequentialGroup()
                        .addComponent(bLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bSalvarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        Statement query = ConexaoPostgreSQL.openConnectionPostgreSQL();
        try{
            ResultSet rs = query.executeQuery("SELECT nome FROM \"Clientes\"");

            while(rs.next()){
                cbDono.addItem(rs.getString("nome"));
            }

        }catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            lbLoginIncorreto.setVisible(true);
        }

        pAddCliente.setPreferredSize(new java.awt.Dimension(700, 350));
        pAddCliente.setVisible(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("ADICIONAR CLIENTE");

        capslock(txtNome1);

        lbNome1.setText("Nome:");

        capslock(txtEndereço);

        lbEndereço.setText("Endereço:");

        jLabel4.setText("Bairro:");

        capslock(txtBairro);

        lbComplemento.setText("Complemento:");

        capslock(txtComplemento);

        lbSexo.setText("Sexo:");

        cbSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione...", "Masculino", "Feminino" }));
        cbSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSexoActionPerformed(evt);
            }
        });

        lbcpf.setText("CPF:");

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lbDataNasc.setText("Data Nasc.:");

        try {
            txtDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lbTelefone1.setText("Telefone 1:");

        try {
            txtTelefone1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lbTelefone2.setText("Telefone 2:");

        try {
            txtTelefone2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lbFaltaNome.setForeground(new java.awt.Color(239, 53, 18));
        lbFaltaNome.setText("*");

        lbFaltaEnd.setForeground(new java.awt.Color(239, 53, 18));
        lbFaltaEnd.setText("*");
        lbFaltaEnd.setVisible(false);

        lbFaltaBairro.setForeground(new java.awt.Color(239, 53, 18));
        lbFaltaBairro.setText("*");
        lbFaltaBairro.setVisible(false);

        lbFaltaData.setForeground(new java.awt.Color(239, 53, 18));
        lbFaltaData.setText("*");
        lbFaltaData.setVisible(false);

        lbFaltaTel.setForeground(new java.awt.Color(239, 53, 18));
        lbFaltaTel.setText("*");
        lbFaltaTel.setVisible(false);

        lbFaltaComp.setForeground(new java.awt.Color(239, 53, 18));
        lbFaltaComp.setText("*");
        lbFaltaComp.setVisible(false);

        lbFaltaCpf.setForeground(new java.awt.Color(239, 53, 18));
        lbFaltaCpf.setText("*");
        lbFaltaCpf.setVisible(false);

        bLimpar1.setText("LIMPAR");
        bLimpar1.setPreferredSize(new java.awt.Dimension(67, 27));
        bLimpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimpar1ActionPerformed(evt);
            }
        });

        bSalvar.setText("SALVAR");
        bSalvar.setPreferredSize(new java.awt.Dimension(4075, 27));
        bSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalvarActionPerformed(evt);
            }
        });

        bVoltar1.setText("VOLTAR");
        bVoltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltar1ActionPerformed(evt);
            }
        });

        lbFaltaSexo.setForeground(new java.awt.Color(239, 53, 18));
        lbFaltaSexo.setText("*");
        lbFaltaSexo.setVisible(false);

        lbFaltaMensagem.setForeground(new java.awt.Color(239, 53, 18));
        lbFaltaMensagem.setText("Por favor preencha os campos restantes *");
        lbFaltaMensagem.setVisible(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pAddClienteLayout = new javax.swing.GroupLayout(pAddCliente);
        pAddCliente.setLayout(pAddClienteLayout);
        pAddClienteLayout.setHorizontalGroup(
            pAddClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAddClienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pAddClienteLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(pAddClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbFaltaEnd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbFaltaNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbFaltaComp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbFaltaTel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbFaltaSexo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pAddClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pAddClienteLayout.createSequentialGroup()
                        .addGroup(pAddClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAddClienteLayout.createSequentialGroup()
                                .addComponent(lbComplemento)
                                .addGap(18, 18, 18)
                                .addComponent(txtComplemento))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAddClienteLayout.createSequentialGroup()
                                .addGroup(pAddClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbEndereço)
                                    .addComponent(lbNome1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addGroup(pAddClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pAddClienteLayout.createSequentialGroup()
                                        .addComponent(txtEndereço, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbFaltaBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAddClienteLayout.createSequentialGroup()
                                .addGroup(pAddClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pAddClienteLayout.createSequentialGroup()
                                        .addComponent(lbSexo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)
                                        .addComponent(lbFaltaCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbcpf))
                                    .addGroup(pAddClienteLayout.createSequentialGroup()
                                        .addComponent(lbTelefone2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtTelefone2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(pAddClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pAddClienteLayout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbFaltaData, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbDataNasc)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAddClienteLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                                        .addGroup(pAddClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbFaltaMensagem)
                                            .addGroup(pAddClienteLayout.createSequentialGroup()
                                                .addGroup(pAddClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(bLimpar1, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                                    .addComponent(bVoltar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addComponent(bSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(pAddClienteLayout.createSequentialGroup()
                                .addComponent(lbTelefone1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(52, Short.MAX_VALUE))
                    .addGroup(pAddClienteLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(193, 193, 193))))
        );
        pAddClienteLayout.setVerticalGroup(
            pAddClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAddClienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(pAddClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNome1)
                    .addComponent(lbFaltaNome))
                .addGap(18, 18, 18)
                .addGroup(pAddClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEndereço, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEndereço)
                    .addComponent(jLabel4)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFaltaEnd)
                    .addComponent(lbFaltaBairro))
                .addGap(18, 18, 18)
                .addGroup(pAddClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbComplemento)
                    .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFaltaComp))
                .addGap(18, 18, 18)
                .addGroup(pAddClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbcpf)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDataNasc)
                    .addComponent(txtDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSexo)
                    .addComponent(lbFaltaData)
                    .addComponent(lbFaltaCpf)
                    .addComponent(lbFaltaSexo))
                .addGap(39, 39, 39)
                .addGroup(pAddClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pAddClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pAddClienteLayout.createSequentialGroup()
                            .addGroup(pAddClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbTelefone1)
                                .addComponent(txtTelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbFaltaTel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(pAddClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbTelefone2)
                                .addComponent(txtTelefone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(bSalvar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pAddClienteLayout.createSequentialGroup()
                        .addComponent(bLimpar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bVoltar1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(pAddClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAddClienteLayout.createSequentialGroup()
                        .addComponent(lbFaltaMensagem)
                        .addContainerGap())))
        );

        lbFaltaNome.setVisible(false);
        lbFaltaNome.setLabelFor(txtNome);

        mCadastro.setText("Cadastro");
        mCadastro.setEnabled(false);

        miAnimal.setText("Animal");
        miAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAnimalActionPerformed(evt);
            }
        });
        mCadastro.add(miAnimal);

        miCliente.setText("Cliente");
        mCadastro.add(miCliente);

        bmBarraMenu.add(mCadastro);

        mClientes.setText("Clientes");
        mClientes.setEnabled(false);

        miBuscarCliente.setText("Buscar");
        mClientes.add(miBuscarCliente);

        bmBarraMenu.add(mClientes);

        mAnimais.setText("Animais");
        mAnimais.setEnabled(false);

        miBuscarAnimal.setText("Buscar");
        mAnimais.add(miBuscarAnimal);

        bmBarraMenu.add(mAnimais);

        mAtendimento.setText("Atendimento");
        mAtendimento.setEnabled(false);

        jMenuItem5.setText("Orçamento");
        mAtendimento.add(jMenuItem5);

        miNovoAtendimento.setText("Novo Atendimento");
        mAtendimento.add(miNovoAtendimento);

        miContultar.setText("Consultar");
        miContultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miContultarActionPerformed(evt);
            }
        });
        mAtendimento.add(miContultar);

        bmBarraMenu.add(mAtendimento);

        setJMenuBar(bmBarraMenu);

        pCadastroAnimal.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
                    .addContainerGap(14, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pCadastroAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addComponent(pAddCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
                    .addGap(13, 13, 13)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pCadastroAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(pAddCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                    .addGap(10, 10, 10)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miAnimalActionPerformed

    private void miContultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miContultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miContultarActionPerformed

    private void bClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClientesActionPerformed
        pMenuPrincipal.setVisible(false);
        pClientes.setVisible(true);
    }//GEN-LAST:event_bClientesActionPerformed

    private void bServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bServicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bServicosActionPerformed

    private void bAnimaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnimaisActionPerformed
        pAnimal.setVisible(true);
        pMenuPrincipal.setVisible(false);
    }//GEN-LAST:event_bAnimaisActionPerformed

    private void bNClientes3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNClientes3ActionPerformed
        pClientes.setVisible(false);
        pAddCliente.setVisible(true);
    }//GEN-LAST:event_bNClientes3ActionPerformed

    private void bBClientes3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBClientes3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bBClientes3ActionPerformed

    private void bVoltar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltar3ActionPerformed
        pClientes.setVisible(false);
        pMenuPrincipal.setVisible(true);
    }//GEN-LAST:event_bVoltar3ActionPerformed

    private void bLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogoutActionPerformed
        pMenuPrincipal.setVisible(false);
        pLogin.setVisible(true);
        txtLogin.setText("");
        txtSenha.setText("");
        mAnimais.setEnabled(false);
        mClientes.setEnabled(false);
        mAtendimento.setEnabled(false);
        mCadastro.setEnabled(false);
        lbAdmin.setText("ADMIN");
        bFuncionario.setEnabled(true);
    }//GEN-LAST:event_bLogoutActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        bEntrarActionPerformed(evt);
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void bSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSairActionPerformed
        this.fechar();
    }//GEN-LAST:event_bSairActionPerformed

    private void bEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEntrarActionPerformed
        Statement query = ConexaoPostgreSQL.openConnectionPostgreSQL();
        int cont = 0;

        try {

            ResultSet rs = query.executeQuery("SELECT id, login, senha, nivel FROM \"Admin\""
                    + "WHERE login = '" + txtLogin.getText() + "' ");

            while (rs.next()) {
                cont++;
                rs = query.executeQuery("SELECT id, login, senha, nivel FROM \"Admin\""
                        + "WHERE senha = '" + txtSenha.getText() + "' ");

                while (rs.next()) {
                    if (rs.getString("login").equals(txtLogin.getText())) {
                        if (rs.getInt("nivel") == 1) {
                            lbAdmin.setText("FUNCIONARIO");
                            bFuncionario.setEnabled(false);
                        }
                        lbLoginIncorreto.setVisible(false);
                        cont++;
                        pLogin.setVisible(false);
                        pMenuPrincipal.setVisible(true);
                        mAnimais.setEnabled(true);
                        mClientes.setEnabled(true);
                        mAtendimento.setEnabled(true);
                        mCadastro.setEnabled(true);
                        lbSenhaIncorreta.setVisible(false);
                    }
                }
            }

            if (cont == 0) {
                lbLoginIncorreto.setVisible(true);
            } else if (cont == 1) {
                lbLoginIncorreto.setVisible(false);
                lbSenhaIncorreta.setVisible(true);
            }

        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            lbLoginIncorreto.setVisible(true);
        }
    }//GEN-LAST:event_bEntrarActionPerformed

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
        txtSenha.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginActionPerformed

    private void bFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bFuncionarioActionPerformed

    private void bNClientes4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNClientes4ActionPerformed
        pCadastroAnimal.setVisible(true);
        pAnimal.setVisible(false);
    }//GEN-LAST:event_bNClientes4ActionPerformed

    private void bBClientes4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBClientes4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bBClientes4ActionPerformed

    private void bVoltar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltar4ActionPerformed
        pMenuPrincipal.setVisible(true);
        pAnimal.setVisible(false);
    }//GEN-LAST:event_bVoltar4ActionPerformed

    private void bVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarActionPerformed
        pCadastroAnimal.setVisible(false);
        pAnimal.setVisible(true);
    }//GEN-LAST:event_bVoltarActionPerformed

    private void bLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimparActionPerformed
        txtNome.setText("");
        txtRaca.setText("");
        cbEspecie.setSelectedItem("-");
        cbDono.setSelectedItem("-");
        bgSexo.clearSelection();
    }//GEN-LAST:event_bLimparActionPerformed

    private void bVoltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltar1ActionPerformed
        pAddCliente.setVisible(false);
        pClientes.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_bVoltar1ActionPerformed

    private void bSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalvarActionPerformed

        //asteriscos campo vazio
        cp.textfield(txtNome1, lbFaltaNome);
        cp.textfield(txtEndereço, lbFaltaEnd);
        cp.textfield(txtBairro, lbFaltaBairro);
        cp.textfield(txtComplemento, lbFaltaComp);
        cp.formattedtextfield(txtCpf, lbFaltaCpf);
        cp.formattedtextfield(txtDataNasc, lbFaltaData);
        cp.formattedtextfield(txtTelefone1, lbFaltaTel);
        cp.combobox(cbSexo, lbFaltaSexo);

        Statement query = ConexaoPostgreSQL.openConnectionPostgreSQL();

        //se todos os campos estiverem preenchidos ele add ao banco de dados
        if ((cp.textfield(txtNome1, lbFaltaNome) == false) && (cp.textfield(txtEndereço, lbFaltaEnd) == false)
                && (cp.textfield(txtBairro, lbFaltaBairro) == false) && (cp.textfield(txtComplemento, lbFaltaComp) == false)
                && (cp.formattedtextfield(txtCpf, lbFaltaCpf) == false) && (cp.formattedtextfield(txtDataNasc, lbFaltaData) == false)
                && (cp.formattedtextfield(txtTelefone1, lbFaltaTel) == false) && (cp.combobox(cbSexo, lbFaltaSexo) == false)) {

            //add
            try {
                query.executeUpdate("INSERT INTO \"Clientes\"(\n"
                        + "            nome, endereco, bairro, complemento, sexo, cpf, datanasc, telefone1, \n"
                        + "            telefone2)\n"
                        + "    VALUES ('" + txtNome1.getText() + "','" + txtEndereço.getText() + "','" + txtBairro.getText()
                        + "','" + txtComplemento.getText() + "','" + cbSexo.getSelectedItem() + "','" + txtCpf.getText()
                        + "', '" + txtDataNasc.getText() + "', '" + txtTelefone1.getText() + "','" + txtTelefone2.getText() + "');");

                JOptionPane.showMessageDialog(null, "Salvo com sucesso!", null, JOptionPane.PLAIN_MESSAGE, null);
                bLimpar1ActionPerformed(evt);//limparcampos

            } catch (Exception e) {
                System.out.println(e);
                JOptionPane.showMessageDialog(null, "Erro na conexão com o banco de dados ", "ERRO", JOptionPane.ERROR_MESSAGE, null);
            }

            lbFaltaMensagem.setVisible(false);
        } else {
            lbFaltaMensagem.setVisible(true);
        }

    }//GEN-LAST:event_bSalvarActionPerformed

    private void bLimpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimpar1ActionPerformed
        txtNome1.setText("");
        txtEndereço.setText("");
        txtComplemento.setText("");
        txtBairro.setText("");
        txtCpf.setText("");
        txtDataNasc.setText("");
        txtTelefone1.setText("");
        txtTelefone2.setText("");
        cbSexo.setSelectedItem(0);
       
    }//GEN-LAST:event_bLimpar1ActionPerformed

    private void cbSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSexoActionPerformed

    private void bSalvarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalvarCadastroActionPerformed
       Statement query = ConexaoPostgreSQL.openConnectionPostgreSQL();
       
            //add
            try {
                query.executeUpdate("INSERT INTO \"Animal\"(\n"
                        + "            nome, sexo, especie, raça, dono)\n"
                        + "    VALUES ('" + txtNome.getText() + "','"+ bgSexo.getSelection().getActionCommand() +"','" + cbEspecie.getSelectedItem()
                        + "','" + txtRaca.getText() + "','" + cbDono.getSelectedItem() + "');");

                JOptionPane.showMessageDialog(null, "Salvo com sucesso!", null, JOptionPane.PLAIN_MESSAGE, null);
                bLimpar1ActionPerformed(evt);//limparcampos

            } catch (Exception e) {
                System.out.println(e);
                JOptionPane.showMessageDialog(null, "Erro na conexão com o banco de dados ", "ERRO", JOptionPane.ERROR_MESSAGE, null);
            }
 
    }//GEN-LAST:event_bSalvarCadastroActionPerformed
    Campovazio cp = new Campovazio();

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicialFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicialFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicialFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicialFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Login().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAnimais;
    private javax.swing.JButton bBClientes3;
    private javax.swing.JButton bBClientes4;
    private javax.swing.JButton bClientes;
    private javax.swing.JButton bEntrar;
    private javax.swing.JButton bFuncionario;
    private javax.swing.JButton bLimpar;
    private javax.swing.JButton bLimpar1;
    private javax.swing.JButton bLogout;
    private javax.swing.JButton bNClientes3;
    private javax.swing.JButton bNClientes4;
    private javax.swing.JButton bSair;
    private javax.swing.JButton bSalvar;
    private javax.swing.JButton bSalvarCadastro;
    private javax.swing.JButton bServicos;
    private javax.swing.JButton bVoltar;
    private javax.swing.JButton bVoltar1;
    private javax.swing.JButton bVoltar3;
    private javax.swing.JButton bVoltar4;
    private javax.swing.ButtonGroup bgSexo;
    private javax.swing.JMenuBar bmBarraMenu;
    private javax.swing.JComboBox cbDono;
    private javax.swing.JComboBox cbEspecie;
    private javax.swing.JComboBox cbSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lSexo;
    private javax.swing.JLabel lbAdmin;
    private javax.swing.JLabel lbComplemento;
    private javax.swing.JLabel lbDataNasc;
    private javax.swing.JLabel lbDono;
    private javax.swing.JLabel lbEndereço;
    private javax.swing.JLabel lbEspecie;
    private javax.swing.JLabel lbFaltaBairro;
    private javax.swing.JLabel lbFaltaComp;
    private javax.swing.JLabel lbFaltaCpf;
    private javax.swing.JLabel lbFaltaData;
    private javax.swing.JLabel lbFaltaEnd;
    private javax.swing.JLabel lbFaltaMensagem;
    private javax.swing.JLabel lbFaltaNome;
    private javax.swing.JLabel lbFaltaSexo;
    private javax.swing.JLabel lbFaltaTel;
    private javax.swing.JLabel lbLogin;
    private javax.swing.JLabel lbLoginIncorreto;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbNome1;
    private javax.swing.JLabel lbRaca;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JLabel lbSenhaIncorreta;
    private javax.swing.JLabel lbSexo;
    private javax.swing.JLabel lbTelefone1;
    private javax.swing.JLabel lbTelefone2;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbTitulo1;
    private javax.swing.JLabel lbcpf;
    private javax.swing.JMenu mAnimais;
    private javax.swing.JMenu mAtendimento;
    private javax.swing.JMenu mCadastro;
    private javax.swing.JMenu mClientes;
    private javax.swing.JMenuItem miAnimal;
    private javax.swing.JMenuItem miBuscarAnimal;
    private javax.swing.JMenuItem miBuscarCliente;
    private javax.swing.JMenuItem miCliente;
    private javax.swing.JMenuItem miContultar;
    private javax.swing.JMenuItem miNovoAtendimento;
    private javax.swing.JLabel nada;
    private javax.swing.JPanel pAddCliente;
    private javax.swing.JPanel pAnimal;
    private javax.swing.JPanel pCadastroAnimal;
    private javax.swing.JPanel pClientes;
    private javax.swing.JPanel pLogin;
    private javax.swing.JPanel pMenuPrincipal;
    private javax.swing.JRadioButton rbFemea;
    private javax.swing.JRadioButton rbMacho;
    private javax.swing.JLabel txtAdmin1;
    private javax.swing.JLabel txtAdmin2;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JFormattedTextField txtDataNasc;
    private javax.swing.JTextField txtEndereço;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNome1;
    private javax.swing.JTextField txtRaca;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JFormattedTextField txtTelefone1;
    private javax.swing.JFormattedTextField txtTelefone2;
    // End of variables declaration//GEN-END:variables

    private void fechar() {
        if (javax.swing.JOptionPane.showConfirmDialog(null, "Deseja sair do programa?", "ATENÇÃO ", javax.swing.JOptionPane.YES_NO_OPTION) == 0) {
            this.dispose();

        }
    }

}
