/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package petshop.GUI;

import petshop.GUI.ConexaoPostgreSQL;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Statement;

/**
 *
 * @author matheus
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexo = new javax.swing.ButtonGroup();
        pLogin = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        lbLogin = new javax.swing.JLabel();
        lbSenha = new javax.swing.JLabel();
        bEntrar = new javax.swing.JButton();
        bSair = new javax.swing.JButton();
        txtSenha = new javax.swing.JPasswordField();
        lbSenhaIncorreta = new javax.swing.JLabel();
        lbLoginIncorreto = new javax.swing.JLabel();
        nada = new javax.swing.JLabel();
        pMenuPrincipal = new javax.swing.JPanel();
        bClientes = new javax.swing.JButton();
        bServicos = new javax.swing.JButton();
        bAnimais = new javax.swing.JButton();
        bFuncionario = new javax.swing.JButton();
        bLogout = new javax.swing.JButton();
        lbAdmin = new javax.swing.JLabel();
        pAnimal = new javax.swing.JPanel();
        bNClientes4 = new javax.swing.JButton();
        bBClientes4 = new javax.swing.JButton();
        bVoltar4 = new javax.swing.JButton();
        txtAdmin2 = new javax.swing.JLabel();
        pClientes = new javax.swing.JPanel();
        bNClientes3 = new javax.swing.JButton();
        bBClientes3 = new javax.swing.JButton();
        bVoltar3 = new javax.swing.JButton();
        txtAdmin1 = new javax.swing.JLabel();
        pCadastroAnimal = new javax.swing.JPanel();
        bVoltar = new javax.swing.JButton();
        lbTitulo1 = new javax.swing.JLabel();
        bLimpar = new javax.swing.JButton();
        bSalvarCadastro = new javax.swing.JButton();
        rbMacho = new javax.swing.JRadioButton();
        rbFemea = new javax.swing.JRadioButton();
        txtNome = new javax.swing.JTextField();
        cbEspecie = new javax.swing.JComboBox();
        cbDono = new javax.swing.JComboBox();
        lbNome = new javax.swing.JLabel();
        lSexo = new javax.swing.JLabel();
        lbEspecie = new javax.swing.JLabel();
        lbRaca = new javax.swing.JLabel();
        lbDono = new javax.swing.JLabel();
        txtRaca = new javax.swing.JTextField();
        bmBarraMenu = new javax.swing.JMenuBar();
        mCadastro = new javax.swing.JMenu();
        miAnimal = new javax.swing.JMenuItem();
        miCliente = new javax.swing.JMenuItem();
        mClientes = new javax.swing.JMenu();
        miBuscarCliente = new javax.swing.JMenuItem();
        mAnimais = new javax.swing.JMenu();
        miBuscarAnimal = new javax.swing.JMenuItem();
        mAtendimento = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        miNovoAtendimento = new javax.swing.JMenuItem();
        miContultar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pLogin.setPreferredSize(new java.awt.Dimension(700, 350));

        lbTitulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("PET SHOP");

        txtLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginActionPerformed(evt);
            }
        });

        lbLogin.setText("Login:");

        lbSenha.setText("Senha:");

        bEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshop/GUI/54.png"))); // NOI18N
        bEntrar.setText("Entrar");
        bEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEntrarActionPerformed(evt);
            }
        });

        bSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshop/GUI/52.png"))); // NOI18N
        bSair.setText("Sair");
        bSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSairActionPerformed(evt);
            }
        });

        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });

        lbSenhaIncorreta.setForeground(new java.awt.Color(255, 0, 0));
        lbSenhaIncorreta.setText("Senha incorreta");
        lbSenhaIncorreta.setVisible(false);

        lbLoginIncorreto.setForeground(new java.awt.Color(255, 0, 0));
        lbLoginIncorreto.setText("Login incorreto");
        lbLoginIncorreto.setVisible(false);

        javax.swing.GroupLayout pLoginLayout = new javax.swing.GroupLayout(pLogin);
        pLogin.setLayout(pLoginLayout);
        pLoginLayout.setHorizontalGroup(
            pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLoginLayout.createSequentialGroup()
                .addContainerGap(245, Short.MAX_VALUE)
                .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nada, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pLoginLayout.createSequentialGroup()
                        .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pLoginLayout.createSequentialGroup()
                                .addComponent(lbSenha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pLoginLayout.createSequentialGroup()
                                    .addComponent(bSair)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bEntrar))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pLoginLayout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(lbTitulo))
                                    .addGroup(pLoginLayout.createSequentialGroup()
                                        .addComponent(lbLogin)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbLoginIncorreto)
                            .addComponent(lbSenhaIncorreta))))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        pLoginLayout.setVerticalGroup(
            pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLoginLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(lbTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(nada, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbLoginIncorreto)
                    .addComponent(lbLogin))
                .addGap(20, 20, 20)
                .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbSenhaIncorreta, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bEntrar)
                    .addComponent(bSair))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pMenuPrincipal.setVisible(false);

        bClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshop/GUI/13.png"))); // NOI18N
        bClientes.setText("<html><body>CLIENTES</body></html>");
        bClientes.setToolTipText("");
        bClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClientesActionPerformed(evt);
            }
        });

        bServicos.setText("<html><body>SERVIÇOS</body></html>");
        bServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bServicosActionPerformed(evt);
            }
        });

        bAnimais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshop/GUI/77.png"))); // NOI18N
        bAnimais.setText("<html><body>ANIMAIS</body></html>");
        bAnimais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnimaisActionPerformed(evt);
            }
        });

        bFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshop/GUI/14.png"))); // NOI18N
        bFuncionario.setText("<html><body>FUNCIONÁRIOS</body></html>");
        bFuncionario.setEnabled(false);
        bFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFuncionarioActionPerformed(evt);
            }
        });

        bLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshop/GUI/52.png"))); // NOI18N
        bLogout.setText("<html><body>LOGOUT</body></html>");
        bLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogoutActionPerformed(evt);
            }
        });

        lbAdmin.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lbAdmin.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbAdmin.setText("ADMIN");

        javax.swing.GroupLayout pMenuPrincipalLayout = new javax.swing.GroupLayout(pMenuPrincipal);
        pMenuPrincipal.setLayout(pMenuPrincipalLayout);
        pMenuPrincipalLayout.setHorizontalGroup(
            pMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMenuPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbAdmin)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pMenuPrincipalLayout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addGroup(pMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addGroup(pMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bServicos, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAnimais, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMenuPrincipalLayout.createSequentialGroup()
                .addContainerGap(593, Short.MAX_VALUE)
                .addComponent(bLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pMenuPrincipalLayout.setVerticalGroup(
            pMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMenuPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAnimais, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(pMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bServicos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(bLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pAnimal.setVisible(false);
        pAnimal.setPreferredSize(new java.awt.Dimension(700, 350));

        bNClientes4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshop/GUI/77.png"))); // NOI18N
        bNClientes4.setText("<html><body>NOVO ANIMAL</body></html>");
        bNClientes4.setToolTipText("");
        bNClientes4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNClientes4ActionPerformed(evt);
            }
        });

        bBClientes4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshop/GUI/77.png"))); // NOI18N
        bBClientes4.setText("BUSCAR ANIMAL");
        bBClientes4.setToolTipText("");
        bBClientes4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBClientes4ActionPerformed(evt);
            }
        });

        bVoltar4.setText("<html><body>VOLTAR</body></html>");
        bVoltar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltar4ActionPerformed(evt);
            }
        });

        txtAdmin2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        txtAdmin2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        txtAdmin2.setText("ANIMAL");

        javax.swing.GroupLayout pAnimalLayout = new javax.swing.GroupLayout(pAnimal);
        pAnimal.setLayout(pAnimalLayout);
        pAnimalLayout.setHorizontalGroup(
            pAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAnimalLayout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addGroup(pAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pAnimalLayout.createSequentialGroup()
                        .addComponent(bNClientes4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(bBClientes4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bVoltar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(pAnimalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtAdmin2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pAnimalLayout.setVerticalGroup(
            pAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAnimalLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(txtAdmin2)
                .addGap(51, 51, 51)
                .addGroup(pAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bNClientes4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBClientes4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(bVoltar4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pClientes.setVisible(false);
        pClientes.setPreferredSize(new java.awt.Dimension(700, 350));

        bNClientes3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshop/GUI/13.png"))); // NOI18N
        bNClientes3.setText("<html><body>NOVO CLIENTE</body></html>");
        bNClientes3.setToolTipText("");
        bNClientes3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNClientes3ActionPerformed(evt);
            }
        });

        bBClientes3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petshop/GUI/13.png"))); // NOI18N
        bBClientes3.setText("BUSCAR CLIENTE");
        bBClientes3.setToolTipText("");
        bBClientes3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBClientes3ActionPerformed(evt);
            }
        });

        bVoltar3.setText("<html><body>VOLTAR</body></html>");
        bVoltar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltar3ActionPerformed(evt);
            }
        });

        txtAdmin1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        txtAdmin1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        txtAdmin1.setText("CLIENTES");

        javax.swing.GroupLayout pClientesLayout = new javax.swing.GroupLayout(pClientes);
        pClientes.setLayout(pClientesLayout);
        pClientesLayout.setHorizontalGroup(
            pClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pClientesLayout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addGroup(pClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pClientesLayout.createSequentialGroup()
                        .addComponent(bNClientes3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(bBClientes3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bVoltar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pClientesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtAdmin1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pClientesLayout.setVerticalGroup(
            pClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pClientesLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(txtAdmin1)
                .addGap(54, 54, 54)
                .addGroup(pClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bNClientes3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBClientes3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(bVoltar3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        bVoltar.setText("<html><body>VOLTAR</body></html>");
        bVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarActionPerformed(evt);
            }
        });

        lbTitulo1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lbTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbTitulo1.setText("Animal");

        bLimpar.setText("LIMPAR");
        bLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimparActionPerformed(evt);
            }
        });

        bSalvarCadastro.setText("<html><body>SALVAR CADASTRO</body></html>");

        bgSexo.add(rbMacho);
        rbMacho.setText("Macho");
        rbMacho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMachoActionPerformed(evt);
            }
        });

        bgSexo.add(rbFemea);
        rbFemea.setText("Fêmea");
        rbFemea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFemeaActionPerformed(evt);
            }
        });

        cbEspecie.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "CACHORRO", "GATO", "CAVALO", "PASSARO", "VEADO(KURAS)", "POKÉMON(PEDRO)" }));

        cbDono.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "JOÃO", "MARIA", "LEK" }));
        cbDono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDonoActionPerformed(evt);
            }
        });

        lbNome.setText("NOME:");

        lSexo.setText("SEXO:");

        lbEspecie.setText("ESPECIE:");

        lbRaca.setText("RAÇA:");

        lbDono.setText("DONO:");

        javax.swing.GroupLayout pCadastroAnimalLayout = new javax.swing.GroupLayout(pCadastroAnimal);
        pCadastroAnimal.setLayout(pCadastroAnimalLayout);
        pCadastroAnimalLayout.setHorizontalGroup(
            pCadastroAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCadastroAnimalLayout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addGroup(pCadastroAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbNome)
                    .addComponent(lSexo)
                    .addComponent(lbEspecie)
                    .addComponent(lbRaca)
                    .addComponent(lbDono))
                .addGap(18, 18, 18)
                .addGroup(pCadastroAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbEspecie, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pCadastroAnimalLayout.createSequentialGroup()
                        .addComponent(rbMacho)
                        .addGap(41, 41, 41)
                        .addComponent(rbFemea)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pCadastroAnimalLayout.createSequentialGroup()
                        .addGroup(pCadastroAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(bSalvarCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))
                    .addComponent(txtNome)
                    .addComponent(cbDono, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtRaca))
                .addContainerGap(137, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pCadastroAnimalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTitulo1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pCadastroAnimalLayout.setVerticalGroup(
            pCadastroAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadastroAnimalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo1)
                .addGap(38, 38, 38)
                .addGroup(pCadastroAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNome))
                .addGap(18, 18, 18)
                .addGroup(pCadastroAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbMacho)
                    .addComponent(rbFemea)
                    .addComponent(lSexo))
                .addGap(18, 18, 18)
                .addGroup(pCadastroAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEspecie))
                .addGap(18, 18, 18)
                .addGroup(pCadastroAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRaca)
                    .addComponent(txtRaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pCadastroAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDono))
                .addGap(16, 16, 16)
                .addGroup(pCadastroAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCadastroAnimalLayout.createSequentialGroup()
                        .addComponent(bLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bSalvarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        mCadastro.setText("Cadastro");
        mCadastro.setEnabled(false);

        miAnimal.setText("Animal");
        miAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAnimalActionPerformed(evt);
            }
        });
        mCadastro.add(miAnimal);

        miCliente.setText("Cliente");
        mCadastro.add(miCliente);

        bmBarraMenu.add(mCadastro);

        mClientes.setText("Clientes");
        mClientes.setEnabled(false);

        miBuscarCliente.setText("Buscar");
        mClientes.add(miBuscarCliente);

        bmBarraMenu.add(mClientes);

        mAnimais.setText("Animais");
        mAnimais.setEnabled(false);

        miBuscarAnimal.setText("Buscar");
        mAnimais.add(miBuscarAnimal);

        bmBarraMenu.add(mAnimais);

        mAtendimento.setText("Atendimento");
        mAtendimento.setEnabled(false);

        jMenuItem5.setText("Orçamento");
        mAtendimento.add(jMenuItem5);

        miNovoAtendimento.setText("Novo Atendimento");
        mAtendimento.add(miNovoAtendimento);

        miContultar.setText("Consultar");
        miContultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miContultarActionPerformed(evt);
            }
        });
        mAtendimento.add(miContultar);

        bmBarraMenu.add(mAtendimento);

        setJMenuBar(bmBarraMenu);

        pCadastroAnimal.setVisible(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
                    .addContainerGap(12, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pCadastroAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pCadastroAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miAnimalActionPerformed

    private void miContultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miContultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miContultarActionPerformed

    private void bClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClientesActionPerformed
        pMenuPrincipal.setVisible(false);
        pClientes.setVisible(true);
    }//GEN-LAST:event_bClientesActionPerformed

    private void bServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bServicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bServicosActionPerformed

    private void bAnimaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnimaisActionPerformed
        pAnimal.setVisible(true);
        pMenuPrincipal.setVisible(false);
    }//GEN-LAST:event_bAnimaisActionPerformed

    private void bNClientes3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNClientes3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bNClientes3ActionPerformed

    private void bBClientes3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBClientes3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bBClientes3ActionPerformed

    private void bVoltar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltar3ActionPerformed
        pClientes.setVisible(false);
        pMenuPrincipal.setVisible(true);
    }//GEN-LAST:event_bVoltar3ActionPerformed

    private void bLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogoutActionPerformed
        pMenuPrincipal.setVisible(false);
        pLogin.setVisible(true);
        txtLogin.setText("");
        txtSenha.setText("");
        mAnimais.setEnabled(false);
        mClientes.setEnabled(false);
        mAtendimento.setEnabled(false);
        mCadastro.setEnabled(false);
        lbAdmin.setText("ADMIN");
        bFuncionario.setEnabled(true);
    }//GEN-LAST:event_bLogoutActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        bEntrarActionPerformed(evt);
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void bSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSairActionPerformed
        this.fechar();
    }//GEN-LAST:event_bSairActionPerformed

    private void bEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEntrarActionPerformed
        Statement query = ConexaoPostgreSQL.openConnectionPostgreSQL();
        int cont = 0;

        try {

            ResultSet rs = query.executeQuery("SELECT id, login, senha, nivel FROM \"Admin\""
                + "WHERE login = '" + txtLogin.getText() + "' ");

            while (rs.next()) {
                cont ++;
                rs = query.executeQuery("SELECT id, login, senha, nivel FROM \"Admin\""
                    + "WHERE senha = '" + txtSenha.getText() + "' ");

                while (rs.next()) {
                    if (rs.getString("login").equals(txtLogin.getText())) {
                        if(rs.getInt("nivel")==1){
                            lbAdmin.setText("FUNCIONARIO");
                            bFuncionario.setEnabled(false);
                        }
                        lbLoginIncorreto.setVisible(false);
                        cont++;
                        pLogin.setVisible(false);
                        pMenuPrincipal.setVisible(true);
                        mAnimais.setEnabled(true);
                        mClientes.setEnabled(true);
                        mAtendimento.setEnabled(true);
                        mCadastro.setEnabled(true);
                        lbSenhaIncorreta.setVisible(false);
                    }
                }
            }

            if (cont == 0) {
                lbLoginIncorreto.setVisible(true);
            } else if (cont == 1) {
                lbLoginIncorreto.setVisible(false);
                lbSenhaIncorreta.setVisible(true);
            }

        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            lbLoginIncorreto.setVisible(true);
        }
    }//GEN-LAST:event_bEntrarActionPerformed

    private void txtLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginActionPerformed
    txtSenha.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoginActionPerformed

    private void bFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bFuncionarioActionPerformed

    private void bNClientes4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNClientes4ActionPerformed
        pCadastroAnimal.setVisible(true);
        pAnimal.setVisible(false);
    }//GEN-LAST:event_bNClientes4ActionPerformed

    private void bBClientes4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBClientes4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bBClientes4ActionPerformed

    private void bVoltar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltar4ActionPerformed
        pMenuPrincipal.setVisible(true);
        pAnimal.setVisible(false);
    }//GEN-LAST:event_bVoltar4ActionPerformed

    private void bVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarActionPerformed
        pCadastroAnimal.setVisible(false);
        pAnimal.setVisible(true);
    }//GEN-LAST:event_bVoltarActionPerformed

    private void bLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimparActionPerformed
        txtNome.setText("");
        txtRaca.setText("");
        cbEspecie.setSelectedItem("-");
        cbDono.setSelectedItem("-");
        bgSexo.clearSelection();
    }//GEN-LAST:event_bLimparActionPerformed

    private void rbMachoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMachoActionPerformed

    }//GEN-LAST:event_rbMachoActionPerformed

    private void rbFemeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFemeaActionPerformed

    }//GEN-LAST:event_rbFemeaActionPerformed

    private void cbDonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDonoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicialFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicialFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicialFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicialFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Login().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAnimais;
    private javax.swing.JButton bBClientes3;
    private javax.swing.JButton bBClientes4;
    private javax.swing.JButton bClientes;
    private javax.swing.JButton bEntrar;
    private javax.swing.JButton bFuncionario;
    private javax.swing.JButton bLimpar;
    private javax.swing.JButton bLogout;
    private javax.swing.JButton bNClientes3;
    private javax.swing.JButton bNClientes4;
    private javax.swing.JButton bSair;
    private javax.swing.JButton bSalvarCadastro;
    private javax.swing.JButton bServicos;
    private javax.swing.JButton bVoltar;
    private javax.swing.JButton bVoltar3;
    private javax.swing.JButton bVoltar4;
    private javax.swing.ButtonGroup bgSexo;
    private javax.swing.JMenuBar bmBarraMenu;
    private javax.swing.JComboBox cbDono;
    private javax.swing.JComboBox cbEspecie;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JLabel lSexo;
    private javax.swing.JLabel lbAdmin;
    private javax.swing.JLabel lbDono;
    private javax.swing.JLabel lbEspecie;
    private javax.swing.JLabel lbLogin;
    private javax.swing.JLabel lbLoginIncorreto;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbRaca;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JLabel lbSenhaIncorreta;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbTitulo1;
    private javax.swing.JMenu mAnimais;
    private javax.swing.JMenu mAtendimento;
    private javax.swing.JMenu mCadastro;
    private javax.swing.JMenu mClientes;
    private javax.swing.JMenuItem miAnimal;
    private javax.swing.JMenuItem miBuscarAnimal;
    private javax.swing.JMenuItem miBuscarCliente;
    private javax.swing.JMenuItem miCliente;
    private javax.swing.JMenuItem miContultar;
    private javax.swing.JMenuItem miNovoAtendimento;
    private javax.swing.JLabel nada;
    private javax.swing.JPanel pAnimal;
    private javax.swing.JPanel pCadastroAnimal;
    private javax.swing.JPanel pClientes;
    private javax.swing.JPanel pLogin;
    private javax.swing.JPanel pMenuPrincipal;
    private javax.swing.JRadioButton rbFemea;
    private javax.swing.JRadioButton rbMacho;
    private javax.swing.JLabel txtAdmin1;
    private javax.swing.JLabel txtAdmin2;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtRaca;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables

    private void fechar() {
        if (javax.swing.JOptionPane.showConfirmDialog(null, "Deseja sair do programa?", "ATENÇÃO ", javax.swing.JOptionPane.YES_NO_OPTION) == 0) {
            this.dispose();
         
        }
    }

}
