/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package petshop.GUI;

/**
 *
 * @author matheus
 */
public class TelaCliente extends javax.swing.JFrame {

    public TelaCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        pClientes = new javax.swing.JPanel();
        bNClientes = new javax.swing.JButton();
        bBClientes = new javax.swing.JButton();
        bVoltar = new javax.swing.JButton();
        txtTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

//        pClientes.setVisible(false);
        pClientes.setPreferredSize(new java.awt.Dimension(700, 350));

        bNClientes.setIcon(new javax.swing.ImageIcon("/home/matheus/Downloads/mimiGlyphs/png/13.png")); // NOI18N
        bNClientes.setText("<html><body>NOVO CLIENTE</body></html>");
        bNClientes.setToolTipText("");
        bNClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNClientesActionPerformed(evt);
            }
        });

        bBClientes.setIcon(new javax.swing.ImageIcon("/home/matheus/Downloads/mimiGlyphs/png/13.png")); // NOI18N
        bBClientes.setText("BUSCAR CLIENTE");
        bBClientes.setToolTipText("");
        bBClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBClientesActionPerformed(evt);
            }
        });

        bVoltar.setIcon(new javax.swing.ImageIcon("/home/matheus/Downloads/mimiGlyphs/png/15.png")); // NOI18N
        bVoltar.setText("<html><body>VOLTAR</body></html>");
        bVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarActionPerformed(evt);
            }
        });

        txtTitulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        txtTitulo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        txtTitulo.setText("CLIENTES");

        javax.swing.GroupLayout pClientesLayout = new javax.swing.GroupLayout(pClientes);
        pClientes.setLayout(pClientesLayout);
        pClientesLayout.setHorizontalGroup(
                pClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pClientesLayout.createSequentialGroup()
                        .addContainerGap(108, Short.MAX_VALUE)
                        .addComponent(bNClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(bBClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(108, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pClientesLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTitulo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pClientesLayout.createSequentialGroup()
                        .addContainerGap(556, Short.MAX_VALUE)
                        .addComponent(bVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pClientesLayout.setVerticalGroup(
                pClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pClientesLayout.createSequentialGroup()
                        .addContainerGap(46, Short.MAX_VALUE)
                        .addComponent(txtTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addGroup(pClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bNClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bBClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(bVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(14, Short.MAX_VALUE))
        );
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        //            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        //                .addGroup(layout.createSequentialGroup()
        //                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        ////                    .addComponent(pMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        //                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        //            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        //                .addGroup(layout.createSequentialGroup()
        //                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        ////                    .addComponent(pClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
        //                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        //            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        //                .addGroup(layout.createSequentialGroup()
        //                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        ////                    .addComponent(pMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        //                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        //            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        //                .addGroup(layout.createSequentialGroup()
        //                    .addContainerGap(13, Short.MAX_VALUE)
        //                    .addComponent(pClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
        //                    .addContainerGap(15, Short.MAX_VALUE)))
        );
        pack();
    }// </editor-fold>                        

    private void bNClientesActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void bBClientesActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void bVoltarActionPerformed(java.awt.event.ActionEvent evt) {
        pClientes.setVisible(false);
//        pMenuPrincipal.setVisible(true);
    }

    // Variables declaration - do not modify   
    private javax.swing.JButton bBClientes;
    private javax.swing.JButton bNClientes;
    private javax.swing.JButton bVoltar;
    private javax.swing.JPanel pClientes;
    private javax.swing.JLabel txtTitulo;
    // End of variables declaration                   

    public javax.swing.JPanel getpClientes() {
        return pClientes;
    }

}
